version: '3.8'

x-shared:
  &common
  NEO4J_AUTH: neo4j/test
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_security_allow__csv__import__from__file__urls: "true"

x-shared-cluster:
  &common-cluster
  <<: *common
  NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000
  NEO4J_dbms_memory_pagecache_size: 100M
  NEO4J_dbms_memory_heap_initial__size: 100M
  NEO4J_causal__clustering_discovery__listen__address: 0.0.0.0:5000
  NEO4J_causal__clustering_transaction__listen__address: 0.0.0.0:6000
  NEO4J_causal__clustering_raft__listen__address: 0.0.0.0:7000

x-shared-core:
  &common-core
  <<: *common-cluster
  NEO4J_dbms_mode: CORE
  NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: 3

networks:
    neo4j:
        driver: bridge

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /opt/project
        networks:
            - neo4j
        volumes:
            - .:/opt/project
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        depends_on:
            - neo4j
            - core1
            - core2
            - core3
            - readreplica1
        expose:
            - 9000
        env_file:
          - .env
    neo4j:
        networks:
            - neo4j
        image: neo4j:4.3-enterprise
        healthcheck:
            test: [ "CMD", "neo4j status" ]
            interval: 30s
            timeout: 10s
            retries: 5
        expose:
            - 7474
            - 7687
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
          <<: *common
        volumes:
          - ./tests/resources:/import
    core1:
        image: neo4j:4.3-enterprise
        healthcheck:
            test: [ "CMD", "neo4j status" ]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - neo4j
        expose:
            - 7474
            - 7686
            - 5000
            - 6000
            - 7000
        ports:
            - "7475:7474"
            - "7688:7687"
        volumes:
          - ./tests/resources:/import
        environment:
          <<: *common-core
          NEO4J_causal__clustering_discovery__advertised__address: core1:5000
          NEO4J_causal__clustering_transaction__advertised__address: core1:6000
          NEO4J_causal__clustering_raft__advertised__address: core1:7000
          NEO4J_dbms_connector_http_advertised__address: core1:7474
          NEO4J_dbms_connector_bolt_advertised__address: core1:7687

    core2:
        image: neo4j:4.3-enterprise
        healthcheck:
            test: [ "CMD", "neo4j status" ]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - neo4j
        expose:
            - 7474
            - 7686
            - 5000
            - 6000
            - 7000
        environment:
          <<: *common-core
          NEO4J_causal__clustering_discovery__advertised__address: core2:5000
          NEO4J_causal__clustering_transaction__advertised__address: core2:6000
          NEO4J_causal__clustering_raft__advertised__address: core2:7000
          NEO4J_dbms_connector_http_advertised__address: core2:7474
          NEO4J_dbms_connector_bolt_advertised__address: core2:7687
        volumes:
          - ./tests/resources:/import

    core3:
        image: neo4j:4.3-enterprise
        healthcheck:
            test: [ "CMD", "neo4j status" ]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - neo4j
        expose:
            - 7474
            - 7686
            - 5000
            - 6000
            - 7000
        environment:
          <<: *common-core
          NEO4J_causal__clustering_discovery__advertised__address: core3:5000
          NEO4J_causal__clustering_transaction__advertised__address: core3:6000
          NEO4J_causal__clustering_raft__advertised__address: core3:7000
          NEO4J_dbms_connector_http_advertised__address: core3:7474
          NEO4J_dbms_connector_bolt_advertised__address: core3:7687
        volumes:
          - ./tests/resources:/import

    readreplica1:
        image: neo4j:4.3-enterprise
        healthcheck:
            test: [ "CMD", "neo4j status" ]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - neo4j
        expose:
            - 7474
            - 7686
            - 5000
            - 6000
            - 7000
        environment:
          <<: *common-cluster
          NEO4J_dbms_mode: READ_REPLICA
          NEO4J_causal__clustering_discovery__advertised__address: readreplica1:5000
          NEO4J_causal__clustering_transaction__advertised__address: readreplica1:6000
          NEO4J_causal__clustering_raft__advertised__address: readreplica1:7000
        volumes:
          - ./tests/resources:/import
