x-shared:
  &common
  NEO4J_AUTH: neo4j/testtest
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_security_allow__csv__import__from__file__urls: "true"
  NEO4J_dbms_security_auth__lock__time: 0s
  NEO4JLABS_PLUGINS: '["apoc"]'

x-shared-cluster:
  &common-cluster
  <<: *common
  NEO4J_causal__clustering_initial__discovery__members: server1:5000,server2:5000,server3:5000
  NEO4J_dbms_memory_pagecache_size: 100M
  NEO4J_dbms_memory_heap_initial__size: 100M
  NEO4J_causal__clustering_discovery__listen__address: 0.0.0.0:5000
  NEO4J_causal__clustering_transaction__listen__address: 0.0.0.0:6000
  NEO4J_causal__clustering_raft__listen__address: 0.0.0.0:7000

x-shared-core:
  &common-core
  <<: *common-cluster
  NEO4J_dbms_mode: CORE
  NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: 3

networks:
  neo4j:
    driver: bridge

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION-8.1}"
    networks:
      - neo4j
    volumes:
      - .:/opt/project
    env_file:
      - .env
    depends_on:
      neo4j:
        condition: service_healthy
      server1:
        condition: service_healthy
      server2:
        condition: service_healthy
      server3:
        condition: service_healthy
      server4:
        condition: service_healthy
  neo4j:
    networks:
      - neo4j
    image: neo4j:4.4-enterprise
    healthcheck:
      test: "wget -q --method=HEAD http://localhost:7474 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      <<: *common
    volumes:
      - ./tests/resources:/import
    env_file:
      - .env
  server1:
    image: neo4j:4.4-enterprise
    healthcheck:
      test: "wget -q --method=HEAD http://localhost:7474 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - neo4j
    volumes:
      - ./tests/resources:/import
    environment:
      <<: *common-core
      NEO4J_causal__clustering_discovery__advertised__address: server1:5000
      NEO4J_causal__clustering_transaction__advertised__address: server1:6000
      NEO4J_causal__clustering_raft__advertised__address: server1:7000
      NEO4J_dbms_connector_http_advertised__address: server1:7474
      NEO4J_dbms_connector_bolt_advertised__address: server1:7687
    env_file:
      - .env

  server2:
    image: neo4j:4.4-enterprise
    healthcheck:
      test: "wget -q --method=HEAD http://localhost:7474 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - neo4j
    environment:
      <<: *common-core
      NEO4J_causal__clustering_discovery__advertised__address: server2:5000
      NEO4J_causal__clustering_transaction__advertised__address: server2:6000
      NEO4J_causal__clustering_raft__advertised__address: server2:7000
      NEO4J_dbms_connector_http_advertised__address: server2:7474
      NEO4J_dbms_connector_bolt_advertised__address: server2:7687
    volumes:
      - ./tests/resources:/import
    env_file:
      - .env

  server3:
    image: neo4j:4.4-enterprise
    healthcheck:
      test: "wget -q --method=HEAD http://localhost:7474 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - neo4j
    environment:
      <<: *common-core
      NEO4J_causal__clustering_discovery__advertised__address: server3:5000
      NEO4J_causal__clustering_transaction__advertised__address: server3:6000
      NEO4J_causal__clustering_raft__advertised__address: server3:7000
      NEO4J_dbms_connector_http_advertised__address: server3:7474
      NEO4J_dbms_connector_bolt_advertised__address: server3:7687
    volumes:
      - ./tests/resources:/import
    env_file:
      - .env

  server4:
    image: neo4j:4.4-enterprise
    healthcheck:
      test: "wget -q --method=HEAD http://localhost:7474 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - neo4j
    environment:
      <<: *common-cluster
      NEO4J_dbms_mode: READ_REPLICA
      NEO4J_causal__clustering_discovery__advertised__address: server4:5000
      NEO4J_causal__clustering_transaction__advertised__address: server4:6000
      NEO4J_causal__clustering_raft__advertised__address: server4:7000
      NEO4J_dbms_connector_http_advertised__address: server4:7474
      NEO4J_dbms_connector_bolt_advertised__address: server4:7687
    env_file:
      - .env
    volumes:
      - ./tests/resources:/import
