version: '3.8'

x-definitions:
  x-shared-env:
    &common-env
    NEO4J_AUTH: neo4j/testtest
    NEO4J_PLUGINS: '["apoc"]'
  x-shared-cluster-env:
    &common-cluster-env
    <<: *common-env
    NEO4J_EDITION: 'enterprise'
    NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
    EXTENDED_CONF: 'yes'
  x-shared-core-env:
    &common-core-env
    <<: *common-cluster-env
    NEO4J_initial_server_mode__constraint: 'PRIMARY'
  x-common:
    &common
    image: neo4j:5.5
    user: ${USER_ID}:${GROUP_ID}
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
    env_file:
      - .env
  x-common-php:
    &common-php
    build:
      context: .
      dockerfile: Dockerfile
    image: neo4j-php-client:latest
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - .:/opt/project
  x-common-cluster:
    &common-cluster
    <<: *common
    image: neo4j:5-enterprise
    networks:
      neo4j-cluster:
        aliases:
          - neo4j-network

networks:
  neo4j:
  neo4j-cluster:

services:
  client:
    <<: *common-php
    networks:
      - neo4j
      - neo4j-cluster
    volumes:
      - .:/opt/project
    env_file:
      - .env
  neo4j:
    <<: *common
    hostname: neo4j
    networks:
      - neo4j
      - neo4j-cluster
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      <<: *common-env
      NEO4J_EDITION: community
    volumes:
      - ./neo4j/neo4j.conf:/conf/neo4j.conf
      - ./neo4j/data/neo4j:/var/lib/neo4j/data
      - ./neo4j/logs/neo4j:/var/lib/neo4j/logs
      - ./neo4j/conf/neo4j:/var/lib/neo4j/conf
      - ./neo4j/import/neo4j:/var/lib/neo4j/import
      - ./neo4j/metrics/neo4j:/var/lib/neo4j/metrics
      - ./neo4j/licenses/neo4j:/var/lib/neo4j/licenses
      - ./neo4j/ssl/neo4j:/var/lib/neo4j/ssl

  server1:
    <<: *common-cluster
    hostname: server1
    ports:
      - "7688:7687"
      - "7475:7474"
    volumes:
      - ./neo4j/neo4j-cluster.conf:/conf/neo4j.conf
      - ./neo4j/data/server1:/var/lib/neo4j/data
      - ./neo4j/logs/server1:/var/lib/neo4j/logs
      - ./neo4j/conf/server1:/var/lib/neo4j/conf
      - ./neo4j/import/server1:/var/lib/neo4j/import
      - ./neo4j/metrics/server1:/var/lib/neo4j/metrics
      - ./neo4j/licenses/server1:/var/lib/neo4j/licenses
      - ./neo4j/ssl/server1:/var/lib/neo4j/ssl
    environment:
      <<: *common-core-env

  server2:
    <<: *common-cluster
    hostname: server2
    ports:
      - "7689:7687"
      - "7476:7474"
    environment:
      <<: *common-core-env
    volumes:
      - ./neo4j/neo4j-cluster.conf:/conf/neo4j.conf
      - ./neo4j/data/server2:/var/lib/neo4j/data
      - ./neo4j/logs/server2:/var/lib/neo4j/logs
      - ./neo4j/conf/server2:/var/lib/neo4j/conf
      - ./neo4j/import/server2:/var/lib/neo4j/import
      - ./neo4j/metrics/server2:/var/lib/neo4j/metrics
      - ./neo4j/licenses/server2:/var/lib/neo4j/licenses
      - ./neo4j/ssl/server2:/var/lib/neo4j/ssl

  server3:
    <<: *common-cluster
    hostname: server3
    ports:
      - "7690:7687"
      - "7477:7474"
    environment:
      <<: *common-core-env
    volumes:
      - ./neo4j/neo4j-cluster.conf:/conf/neo4j.conf
      - ./neo4j/data/server3:/var/lib/neo4j/data
      - ./neo4j/logs/server3:/var/lib/neo4j/logs
      - ./neo4j/conf/server3:/var/lib/neo4j/conf
      - ./neo4j/import/server3:/var/lib/neo4j/import
      - ./neo4j/metrics/server3:/var/lib/neo4j/metrics
      - ./neo4j/licenses/server3:/var/lib/neo4j/licenses
      - ./neo4j/ssl/server3:/var/lib/neo4j/ssl

  server4:
    <<: *common-cluster
    hostname: server4
    ports:
      - "7691:7687"
      - "7478:7474"
    environment:
      <<: *common-cluster-env
      NEO4J_initial_server_mode__constraint: 'SECONDARY'
    volumes:
      - ./neo4j/neo4j-cluster.conf:/conf/neo4j.conf
      - ./neo4j/data/server4:/var/lib/neo4j/data
      - ./neo4j/logs/server4:/var/lib/neo4j/logs
      - ./neo4j/conf/server4:/var/lib/neo4j/conf
      - ./neo4j/import/server4:/var/lib/neo4j/import
      - ./neo4j/metrics/server4:/var/lib/neo4j/metrics
      - ./neo4j/licenses/server4:/var/lib/neo4j/licenses
      - ./neo4j/ssl/server4:/var/lib/neo4j/ssl
