version: '3.2'

networks:
    neo4j:
        driver: bridge

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - WITH_XDEBUG=true
        working_dir: /opt/project
        networks:
            - neo4j
        volumes:
            - .:/opt/project
        depends_on:
            - neo4j-42
        expose:
            - 9000
        environment:
            - XDEBUG_MODE=coverage
    neo4j-42:
        networks:
            - neo4j
        image: neo4j:4.2
        expose:
            - 7474
            - 7687
        environment:
            - NEO4J_AUTH=neo4j/test
