name: Integration Tests On Single Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CONNECTIONS: neo4j://neo4j:testtest@localhost,bolt://neo4j:testtest@localhost,http://neo4j:testtest@localhost
    name: "Running on PHP ${{ matrix.php-version }} with a Neo4j ${{ matrix.neo4j-version }} instance"
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.0", "8.2"]
        neo4j-version: ["4.4", "5.1", "5.5"]

    services:
      neo4j:
        image: neo4j:${{ matrix.neo4j-version }}
        env:
          NEO4J_AUTH: neo4j/testtest
          NEO4JLABS_PLUGINS: '["apoc"]'
        ports:
          - 7687:7687
          - 7474:7474
        options: >-
          --health-cmd "wget -q --method=HEAD http://localhost:7474 || exit 1"
          --health-start-period "60s"
          --health-interval "30s"
          --health-timeout "15s"
          --health-retries "5"

    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: ${{ matrix.php-version }}
          version: 2
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          memory_limit: 1024M
          version: 9
          testsuite: Integration
          bootstrap: vendor/autoload.php
