name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests-v4:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1.31', '8.3.17']
    name: "Running on PHP ${{ matrix.php }} with a Neo4j 4 instance connecting over all available protocols"

    steps:
      - uses: actions/checkout@v4
      - name: Populate .env
        run: |
          echo "PHP_VERSION=${{ matrix.php }}" > .env
          echo "CONNECTION=neo4j://neo4j:testtest@neo4j" >> .env
      - uses: hoverkraft-tech/compose-action@v2.0.2
        name: Start services
        with:
          compose-file: './docker-compose-neo4j-4.yml'
          up-flags: '--build --remove-orphans'
      - name: Composer install
        run: |
          docker compose run client composer install
      - name: Test neo4j://
        run: |
          docker compose run \
            -e PHP_VERSION=${{ matrix.php }} \
            -e CONNECTION=neo4j://neo4j:testtest@neo4j \
            client ./vendor/bin/phpunit -c phpunit.xml.dist --testsuite Integration
      - name: Test bolt://
        run: |
          docker compose run \
            -e PHP_VERSION=${{ matrix.php }} \
            -e CONNECTION=bolt://neo4j:testtest@neo4j \
            client ./vendor/bin/phpunit -c phpunit.xml.dist --testsuite Integration
  tests-v5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1.31', '8.3.17']
    name: "Running on PHP ${{ matrix.php }} with a Neo4j 5 instance connecting over all available protocols"

    steps:
      - uses: actions/checkout@v4
      - name: Populate .env
        run: |
          echo "PHP_VERSION=${{ matrix.php }}" > .env
          echo "CONNECTION=neo4j://neo4j:testtest@neo4j" >> .env
      - uses: hoverkraft-tech/compose-action@v2.0.2
        name: Start services
        with:
          compose-file: './docker-compose.yml'
          up-flags: '--build'
      - name: Composer install
        run: |
          docker compose run client composer install
      - name: Test neo4j://
        run: |
          docker compose run \
            -e PHP_VERSION=${{ matrix.php }} \
            -e CONNECTION=neo4j://neo4j:testtest@neo4j \
            client ./vendor/bin/phpunit -c phpunit.xml.dist --testsuite Integration
      - name: Test bolt://
        run: |
          docker compose run \
            -e PHP_VERSION=${{ matrix.php }} \
            -e CONNECTION=bolt://neo4j:testtest@neo4j \
            client ./vendor/bin/phpunit -c phpunit.xml.dist --testsuite Integration
