name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: integration-tests-aura
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        php: ["8.1.31", "8.3.17"]
    name: "Running on all provided Aura instances"
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "PHP_VERSION=${{ matrix.php }}" > .env
          echo "CONNECTION=\"${{ secrets.AURA_PRO }}\"" >> .env

          docker compose run --rm --no-deps \
            client sh -c "composer install && ./vendor/bin/phpunit -c phpunit.xml.dist --testsuite Integration"
