name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: "Running on PHP 8.1 with a Neo4j 5 instance connecting over all available protocols"

    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
      - name: Populate .env
        run: |
          echo "CONNECTION=neo4j://neo4j:testtest@neo4j" > .env
      - uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: './docker-compose.yml'
          up-flags: '--build'
      - name: Composer install
        run: |
          docker compose run client composer install
      - name: Test neo4j://
        run: |
          docker compose run -e CONNECTION=neo4j://neo4j:testtest@localhost client ./vendor/bin/phpunit -c phpunit.xml.dist --testsuite Integration
      - name: Test bolt://
        run: |
          docker compose run -e CONNECTION=bolt://neo4j:testtest@localhost client ./vendor/bin/phpunit -c phpunit.xml.dist --testsuite Integration
      - name: Test http://
        run: |
          docker compose run -e CONNECTION=http://neo4j:testtest@localhost client ./vendor/bin/phpunit -c phpunit.xml.dist --testsuite Integration
